### ISSUE TITLE
Updating ROMS.jl dependence on NCDatasets.jl to v0.13+?

### ISSUE THREAD

**Issue by truedichotomy** [Alexander-Barth/ROMS.jl#11]
ROMS.jl currently has dependence for NCDatasets v0.12.7. This is problematic for Julia v1.10, but this seems to be addressed by NCDatasets v0.13+. Can this dependency of ROMS.jl be updated? Thanks!

**Comment by Alexander-Barth** [comment]
I just release a new version of DIVAnd which was holding back on using NCDatasets v0.13+.
