### ISSUE TITLE
Coriolis is calculated using cosine

### ISSUE THREAD

**Issue by lnferris** [Alexander-Barth/ROMS.jl#15]
Why is the Coriolis parameter calculated using cosine instead of sine? I think is producing the wrong Coriolis parameters

https://github.com/Alexander-Barth/ROMS.jl/blob/169da59efaa0c76f7325fc089b99248f371f5786/src/generate_config.jl#L28

**Comment by lnferris** [comment]
Also omega is too small https://www.teos-10.org/pubs/gsw/pdf/f.pdf

**Comment by Alexander-Barth** [comment]
Thanks a lot, you are right! (must have been late when I wrote this).

**Comment by lnferris** [comment]
Thanks for your prompt attention! I think you and I (since I am clearly also invested in improving ROMS.jl) should make an effort to go through and second-check some of the functions to make sure there aren't any other significant sleep deprivation errors waiting for us. I am looking at the grid file creation currently.

**Comment by Alexander-Barth** [comment]
You are welcome! Thanks again for reporting this!
