### ISSUE TITLE
Test case LigurianSea has Blowing-up error, possible grid issue?

### ISSUE THREAD

**Issue by nishadhka** [Alexander-Barth/ROMS.jl#4]
Thanks for the detailed tutorial on ROMS simulation. As given in the page https://alexander-barth.github.io/ROMS.jl/dev/. 
Using the provided input data and source code, https://dox.ulg.ac.be/index.php/s/nH8u2DrI1m9mMbC preprocessing step completed without any issue. 

The test case is built on a docker machine and a change is needed for compilation, which is noted in https://github.com/nishadhka/ROMS.jl/blob/master/test/testcase_liguriansea/Readme.rst
However the simulation gets blownup issue, after changing the DS to 50 seconds, the simulation could run for 3 hours then ends up in same Blowing-up error. The modified roms.in https://github.com/nishadhka/ROMS.jl/blob/master/test/testcase_liguriansea/roms.in and roms.out ishttps://github.com/nishadhka/ROMS.jl/blob/master/test/testcase_liguriansea/roms.out  uploaded. 

For a debug purposes, made a visualisation of simulation restart files, the speicfic variable `mask_rho` shows an abnormal mask values over east land region as like in ocean. 
![Screenshot_2022-05-06_14-21-09](https://user-images.githubusercontent.com/3928997/167103684-d70f21b7-ad73-46c7-b580-fab42b31aaa7.png)

**Comment by Alexander-Barth** [comment]
I cannot reproduce this. This is the mask that I get 

![Figure_1](https://user-images.githubusercontent.com/9881475/167134727-8edf1eb0-b166-492f-837b-8be774ac35d5.png)

To run the test case and make this plot:

```julia
]test ROMS
# cd to ~/ROMS-implementation-test/Simulation1 
using PyPlot, NCDatasets
pcolor(NCDataset("roms_rst.nc")["mask_rho"][:,:]')
```

**Comment by nishadhka** [comment]
Thanks for the test routine. I totally missed the last part involving https://github.com/Alexander-Barth/ROMS.jl/blob/master/test/example_config_next.jl marked in test routine https://github.com/Alexander-Barth/ROMS.jl/blob/4ea15bdc5945517c6dbb9b8b3646bc65ab889526/test/runtests.jl#L112. Executed only the https://github.com/Alexander-Barth/ROMS.jl/blob/master/test/example_config.jl, and then the simulation, the error would be due to this. Closing the ticket.

**Comment by Alexander-Barth** [comment]
Here is the diff between your roms.in and my roms.in. The `LBC` variables are still set to a periodic boundary condition which explains why you have this issue in the mask. 

$ diff roms.in ROMS-implementation-test/Simulation1/roms.in 


```diff
4c4
< !svn $Id: roms.in 1022 2020-05-13 03:03:15Z arango $
---
> !svn $Id: roms.in 1054 2021-03-06 19:47:12Z arango $
6c6
< !  Copyright (c) 2002-2020 The ROMS/TOMS Group                                !
---
> !  Copyright (c) 2002-2021 The ROMS/TOMS Group                                !
67c67
<        TITLE = Wind-Driven Upwelling/Downwelling over a Periodic Channel
---
>        TITLE = My test
71c71
<     MyAppCPP = LigurianSea
---
>     MyAppCPP = UPWELLING
76c76
<      VARNAME = /root/ROMS-implementation-test/varinfo.dat
---
>      VARNAME = /home/abarth/ROMS-implementation-test/Simulation1/varinfo.dat
184,189c184,189
<    LBC(isFsur) ==   Per     Clo     Per     Clo         ! free-surface
<    LBC(isUbar) ==   Per     Clo     Per     Clo         ! 2D U-momentum
<    LBC(isVbar) ==   Per     Clo     Per     Clo         ! 2D V-momentum
<    LBC(isUvel) ==   Per     Clo     Per     Clo         ! 3D U-momentum
<    LBC(isVvel) ==   Per     Clo     Per     Clo         ! 3D V-momentum
<    LBC(isMtke) ==   Per     Clo     Per     Clo         ! mixing TKE
---
>    LBC(isFsur) == Cha Cha Clo Clo         ! free-surface
>    LBC(isUbar) == Fla Fla Clo Clo         ! 2D U-momentum
>    LBC(isVbar) == Fla Fla Clo Clo         ! 2D V-momentum
>    LBC(isUvel) == RadNud RadNud Clo Clo         ! 3D U-momentum
>    LBC(isVvel) == RadNud RadNud Clo Clo         ! 3D V-momentum
>    LBC(isMtke) == Rad Rad Clo Clo         ! mixing TKE
[...]
```

**Comment by Alexander-Barth** [comment]
I expanded the part in the lecture about the LBC variable (which I explained only orally during the lecture):

https://github.com/Alexander-Barth/ROMS.jl/commit/8e2911dece4ab0d71417fe20156153e652e550b4
