### ISSUE TITLE
Motu

### ISSUE THREAD

**Issue by bluerror2710** [Alexander-Barth/ROMS.jl#6]
Dear Alexander

First, I want thank you for your magnificent work. I want to know how can I edit the service_id and motu_server, because it doesnt work anymore because the Motu server no longer supported "MEDSEA_MULTIYEAR_PHY_006_004-TDS" and no matter how I change the Motu id and other paths, the code give me the following error. Please help me with this issu.
![Capture](https://user-images.githubusercontent.com/108568984/180601371-7c40af3a-6fdd-45ee-9b28-cf6c73dd549c.PNG)

**Comment by Alexander-Barth** [comment]
Thanks for your encouragements! I am currently out of office. If you would look in the cmems catalog https://marine.copernicus.eu/ for the Mediterranean sea model you can see the corresponding Motu script with all arguments than you need to use. According to the ci logs, the Motu code still worked 12 days ago. "Connection reset by peer" might be also a temporary server issue. The chat feature on the cmems website was quite helpful in the past. When you copy the Motu command in a terminal you would able to reproduce the issue indepently from ROMS.jl

**Comment by Bluerrror** [comment]
Sorry. But I dont know what you say man. Please help me. I am stuck. There is no motu server that contain such data.

**Comment by Bluerrror** [comment]
Found it. It was local network problem.

**Comment by Alexander-Barth** [comment]
Ah, ok it seems that you are using the virtual machine. In this case, you need to update ROMS.jl. Can you open a terminal and issue the following commands:

```bash
cd ~/.julia/dev/ROMS
git pull
```

And restart Julia / the jupyter kernel. If you see an error message, please paste a full copy here. Avoid screen shot, when possible. You can connect to GitHub from the browser in the VM if copy pasting from VM to host is a problem .

**Comment by bluerror2710** [comment]
Thank you for your absolutely amazing tutorial and methods that you implemented to model with ROMS. I used your solution and it is working now. :-D
