### ISSUE TITLE
HYCOM 3-hourly IC and BC or tidal forces implementation 

### ISSUE THREAD

**Issue by bluerror2710** [Alexander-Barth/ROMS.jl#8]
Dear Alexander

I want to thank you first for your work. I actually want to know, how can I impose BCs by tidal forces (M2, S2, or ...) to solve model for hourly resolution in Global Scale or use HYCOM 3-hourly IC and BC. Can you help me with this issue?

**Comment by bluerror2710** [comment]
Dear Alexander

Any news could help me. Please let me know

**Comment by bluerror2710** [comment]
Dear Alexander 

Sorry for inconvenience. Any news could help me.

**Comment by Alexander-Barth** [comment]
Can you confirm that the HYCOM 3-hourly output already includes tides?

If  yes, you might try to use this HYCOM 3-hourly output to generate the IC  and BC files as usual.

**Comment by bluerror2710** [comment]
Sorry for delay. Actually, I implemented tidal forces plus CMEMS to get reasonable outputs. By the way, I don't think  so, the HYCOM included tides. 
However, could you implement HYCOM 3-hourly output for boundary conditions?

**Comment by Alexander-Barth** [comment]
Is the format of the 3 hourly output Hycom different from the daily output? If not, then maybe the present code might already work by providing the appropriate opendap URL to the Hycom function. If this doesn't work (with the latest version of ROMS jl) please report here the full error message.
